### ISSUE TITLE
Cannot load such file -- roar/representer/json

### ISSUE THREAD

**Issue by kgish** [apotonick/roar#121]
When I try to run the example application/server I get the following error message:
```bash
$ beru example_server.rb 
example_server.rb:6:in `require': cannot load such file -- 
   roar/representer/json (LoadError) from example_server.rb:6:in `<main>'
```

**Comment by apotonick** [comment]
That's because we haven't updated the examples for Roar 1.0! Are you keen to do that? https://github.com/apotonick/roar/blob/master/CHANGES.markdown#breakage

**Comment by kgish** [comment]
Sure I will give it a try.

**Comment by kgish** [comment]
Finished, see pull request.

**Comment by apotonick** [comment]
Thanks brother! :heart:

**Comment by kgish** [comment]
Sure, anytime.
