### ISSUE TITLE
 Big changes on JSON-API v1.0 rc2

### ISSUE THREAD

**Issue by oliverbarnes** [apotonick/roar#131]
rc2 comes with a [considerable rewrite of the spec](https://github.com/json-api/json-api/pull/341) before stabilizing into 1.0. I'm still making sense o them, will update with more info later.

In any case, I'd wait for final 1.0 to be released before touching anything, to avoid further surprises :)

**Comment by apotonick** [comment]
Thanks for keeping me uptodate on this. Doesn't look too hectic, but last time I said this it took weeks to implement the changes haha.

**Comment by thegcat** [comment]
I think this is superseded by #141 (JSON API RC3).

**Comment by apotonick** [comment]
All done. http://trailblazer.to/gems/roar/jsonapi.html
