### ISSUE TITLE
Release 1.0.1 to rubygems

### ISSUE THREAD

**Issue by rupurt** [apotonick/roar#138]
Hi,

I noticed that the [last commit](https://github.com/apotonick/roar/commit/958299b6a6fe3458015b30e99e797398a9531492) is a release for 1.0.1 but it doesn't look like you've released it to [rubygems](https://rubygems.org/gems/roar).

**Comment by apotonick** [comment]
Hey Alex, I wasn't sure if this is crucial. Since the JSON-API specification keeps changing every other day I decided to wait with releases, but I can push it for you if you buy me a beer one day.

**Comment by rupurt** [comment]
Haha no worries. I'd buy a fellow aussie a beer any day for your work on the trailblazer stuff.

We're pulling the gem from master so if you'd prefer not to release that's fine.

**Comment by apotonick** [comment]
Haha I'm an idiot. I didn't push the already "released" gem to rubygems. Actually pushed just now, enjoy!

**Comment by rupurt** [comment]
:+1:
