### ISSUE TITLE
Introspection, API documentation, and testing

### ISSUE THREAD

**Issue by moxley** [apotonick/roar#139]
Hey, thanks for the wonder `representable` and `roar` gems! We use them heavily here at https://github.com/househappy (Do you need help maintaining these gems? We might be able to help.). Our API documentation process is in bad need of some improvement. We currently use Yard doc, manually maintaining endpoint documentation in our controller action comments. It's an error-prone process that easily gets out of date. I know that there are much better API documentation solutions out there, but they seem to all involve adopting a replacement of representable/roar-- an inferior replacement at that. I can see that a representable definition is just a type of document schema, and I was thinking why not extend that into a full-blown API documentation solution? We would also like to generate example API responses, using the representer definition as a basis for generating test data. Do you have any suggestions?

**Comment by syntaxritual** [comment]
Moxley,

You might find https://github.com/zipmark/rspec_api_documentation of use.
I've used it with success on several projects, check out some sample output
here: http://rad-example.herokuapp.com/docs/orders/creating_an_order .

Cheers!
_travis

**Comment by apotonick** [comment]
Hey Moxley,

I can help you with the representable API or maybe even add a module for introspection. I love the idea of automatic documentation and representable/Roar is a perfect fit for that, since it, as you said, defines the document syntax.

You can start with the following code.

```ruby
Representer.representable_attrs.definitions
```

**Comment by moxley** [comment]
Thanks @apotonick. We actually use `representable_attrs.definitions` to help streamline our tests. We use it to ensure an API endpoint returns data that includes properties that match the expected Representer.

Here's some the code we use:

```ruby
    representer.representable_attrs[:definitions].map do |d|
      next if d.send(:instance_variable_get, :@options)[:readable] == false
      d.send(:instance_variable_get, :@options)[:as]
    end.compact
```

It's a good start, but as you can see, much of the property definition seems to be hidden behind instance variables.

**Comment by moxley** [comment]
@syntaxritual Thanks for the suggestion. I haven't had a chance to look into `rspec_api_documentation` yet, but eventually, we will, as we make it a priority to upgrade our documentation process.

**Comment by apotonick** [comment]
@moxley You don't need to access instance variables, you can do that.

```ruby
definition[:readable]
```

**Comment by moxley** [comment]
Excellent, I'll access the `definition` hash directly. Thanks @apotonick!

**Comment by moxley** [comment]
Thanks @apotonick. After spending some time with it, this is as far as I got:

```ruby
    representer.representable_attrs[:definitions].map do |d|
      next if d[:readable] == false
      d.send(:instance_variable_get, :@options)[:as]
    end.compact
```

`d[:as]` is a Uber::Options::Value instance. I don't know how to access the passed-in `:as` value from that, so this still accesses the `@options` ivar directly. I'm actually thinking of forbidding the use of `:as` in our app, and just use `:getter` instead. That way, the property name defined is always the property name in the document.

**Comment by apotonick** [comment]
You can use `Definition#name` instead of the `:as` option!
