### ISSUE TITLE
JSON-API rc3

### ISSUE THREAD

**Issue by oliverbarnes** [apotonick/roar#141]
Hey Nick, the latest release candidate if you haven't seen it already: [pull request](https://github.com/json-api/json-api/pull/483) and [diff](https://github.com/json-api/json-api/compare/gh-pages@%7B2weeks%7D...gh-pages)

**Comment by apotonick** [comment]
A list of changes we need in Roar would be awesome, I really don't use JSON-API (yet) and have no idea about what changed this time. Any help appreciated! <3

**Comment by oliverbarnes** [comment]
sure thing. I'm going to use it today and will try to compile a list of changes. If I have time I'd love to contribute a PR too, let's see how it goes :)

**Comment by bvandenbos** [comment]
Any update on this?  I'm new to JSON-API but am very interested in using Roar w/ RC3.  Just curious how much effort it will be to get it up to spec and if there's a way I could help out.

**Comment by bvandenbos** [comment]
There's a specific question I have regarding the spec that I'll post here as well (although I'm not sure it's related to RC3 or not).  The spec calls out:

> Primary data MUST appear under a top-level key named "data". 

However, Roar::JSON::JSONAPI seems to return data keyed by the type instead of `data`.  Further more, ut doesn't include `type` in the attributes hash.  I'm unable to tell if (a) I'm using it wrong or am missing something, (b) it's coded to an old version of the spec that worked differently, or (c) it's broken.

**Comment by apotonick** [comment]
The current implemention in Roar is following the old spec. Reason for this is that they keep changing things. I personally don't use JSON-API so if anyone can outline what to change I'm happy to do so!!!

**Comment by bvandenbos** [comment]
Ok - that explains my confusion.  Thanks.  I'd love to help out but I also don't have a deep JSON-API understanding just yet.

**Comment by thegcat** [comment]
I'm currently working on getting the tests updated to the RC3 spec, this should be done tonight (if I can get my head wrapped around 1 or 2 details left that is…).

I also have some changes to `APIJSON` proper that make some tests pass, but I'm far from sure that that would be the "canonical" way to solve this :sweat_smile:

**Comment by thegcat** [comment]
There's one thing I'm absolutely not sure about that maybe one of you or @steveklabnik could help me with: are link templates still a thing in JSON API RC3, or have they never been and they are in the roar tests because of things?

I mean structures like:

``` ruby
            "links" => {
              "songs.album"=> {
                "href"=>"http://example.com/albums/{songs.album}", "type"=>"album"
              }
            }
```

See https://github.com/apotonick/roar/blob/master/test/json_api_test.rb#L135-L139

**Comment by steveklabnik** [comment]
Templates went away in RC3.

**Comment by thegcat** [comment]
I guess they're superseded by `links.self` in the `included` objects if needed?

Anyway, that should help me finish adapting the tests for JSON-API RC3, thanks @steveklabnik!

**Comment by thegcat** [comment]
See pull request in #143, I'd appreciate any kind of input to get the tests and code up to speed :-)

**Comment by apotonick** [comment]
Thanks @thegcat for your help (And @steveklabnik for answering so prompt :heart: )! I wonder if that is all we need to get RC3 running?

**Comment by thegcat** [comment]
@apotonick The existing tests are as far as I can tell all "upgraded" to RC3, maybe someone else/better informed about JSON API could confirm this.

The code as I said is another thing, especially converting a list of numerical IDs to a list of `{ "linkage": { "type": "sometype", "id": "someid" } }` is not simple, and I don't see a good way that a representer with `links` in that format created "by hand" can parse an incoming document, so I'm thinking about not trying this "by hand" and only offer the `has_one` and `has_many` helpers. I've come up with the following for a single item:

``` ruby
nested :album do
  nested :linkage do
    property :type, writable: false, getter: ->(_) { 'albums' }
    property :album_id, :as => :id
  end
end
```

but I don't linke it, so I might remove those from the tests to prefer the `has_one` and `has_many` methods for those cases.

There's also a lot of other cases the tests currently don't cover, for example when the `data.links.something` is an URL instead of a `linkage` object and so on. That should probably be added after the existing tests are passing.

**Comment by felixbuenemann** [comment]
JSON API 1.0 is [released](http://www.cerebris.com/blog/2015/06/04/jsonapi-1-0/) so I guess now would be a good idea to update the implementation.

**Comment by apotonick** [comment]
I just checked it, and it has completely changed, again, since the last time I worked with it.

I am not using JSON-API and I am definitely not gonna spend hours to read and understand 20 pages of specification. You guys have to help and tell me what in our current implementation is wrong.

**Comment by oliverbarnes** [comment]
Hey guys, since I opened this issue I ended up switching to jsonapi-resources, just because a client of ours required it for a project. Sorry Nick for not contributing the update, it's been crazy the last few months :/ Closing this

**Comment by apotonick** [comment]
We still have to implement it at some point, though. :wink:

**Comment by apotonick** [comment]
Once you see how perfectly Reform forms now integrate with representers, and can be used to validate a parsed JSON-API object graph, you will come back here, with tears in your eyes, and we will welcome you with open arms hahaha.

**Comment by oliverbarnes** [comment]
Ok, just closed because rc3 doesn't need to be supported, now that final 1.0 is out. I'll be sure to check out Reform forms - I've been reading the Trailblazer book, and the ruby rogues interview was very interesting. Even if I end up not using the actual tools, I'm already learning a lot from your view on things! Thanks dude

**Comment by felixbuenemann** [comment]
Sadly the JSON API repo has no tags before 1.0 or a changelog to help implementers in updating. Or I'm too stupid to find it ;-)

**Comment by apotonick** [comment]
Sorry, I was talking about our tests :grimacing: https://github.com/apotonick/roar/blob/master/test/json_api_test.rb

There, you can see our old assumptions and maybe point me to the change-relevant details. Thanks! :beers:

**Comment by thegcat** [comment]
IIRC the 1.0 final was more or less the same as RC3, so #143 is still a very good start to adapt the tests to the 1.0 final spec. (I think @steveklabnik already told me there was no significant change from RC3 to 1.0 final, but I can't find where :cry: )

I can see about reviewing #143 and check it for 1.0 final compatibility.

**Comment by felixbuenemann** [comment]
@thegcat That would be great. I recently tested the current JSON-API support in roar and the type based top level keys used by the older spec made me switch back to using the JSON representer with the JSON::HAL::Links module for hypermedia.

**Comment by steveklabnik** [comment]
Yeah, RC3 -> final was mostly about cleaning up language, not about changing anything functionally.

**Comment by thegcat** [comment]
I have gone through `JSONAPITest` in #143 again to make the hash representation conform to the JSON API 1.0 spec. I wouldn't mind a second pair of eyes on it, but that should be a good place to start the implementation.

I haven't touched much code as there's probably a few decisions to make (infer the `type`, and if so always inflect it to plural, and so on).

@apotonick if you point me in the direction you want to take this, I can try to work my way through the code and propose some stuff.

**Comment by felixbuenemann** [comment]
@thegcat Did you forget to push your commits? Last commit in #143 is from Apr 28th.

**Comment by apotonick** [comment]
Hey friends,

I changed something in Representable which might help us make the JSONAPI implementation simpler, so we should be able to release a JSON-API 1.0 version soon.

Also, I'm coming to the last chapter soon with the Trailblazer book, where I plan to demonstrate how to setup a JSON API, so I kinda need this feature!!! :wink: :stuck_out_tongue_winking_eye:

**Comment by felixbuenemann** [comment]
BDD – Book Driven Development? :wink:

**Comment by apotonick** [comment]
Actually, that is pretty much spot on... :grimacing:

**Comment by thegcat** [comment]
@felixbuenemann TL;DR: no, I had not forgotten to push.

GitHub for some reason shows the authored, not the commit date.

thegcat/roar@bac682d for example was authored first in April, but as I rebased and updated it the commit date is yesterday (the dates at the end are the committed and authored date):

```
* 79d8141 (Felix Schäfer) (HEAD -> 141-jsonapi_rc3, origin/141-jsonapi_rc3) `linked` changed to `included` #141 [Sun Jul 12 22:52:44 2015 +0200, Tue Apr 28 16:52:38 2015 +0200]
* 6245ae3 (Felix Schäfer) Top key changed to "data", `type` included in object #141 [Sun Jul 12 22:52:44 2015 +0200, Tue Apr 28 16:51:38 2015 +0200]
* bac682d (Felix Schäfer) Update JSONAPI tests to JSON API 1.0 format #141 [Sun Jul 12 22:52:44 2015 +0200, Tue Apr 28 16:48:12 2015 +0200]
```

**Comment by thegcat** [comment]
(@felixbuenemann and if you're wondering how this might happen: I have rebased my old Pull Request and edited the first commit that was supposed to update the tests to the current (then RC3, now 1.0) JSON API version, which is why the commits have been authored end of April but committed yesterday)

**Comment by felixbuenemann** [comment]
@thegcat Yeah, I didn't think of that. At least for amending I tend to use `--reset-author` to update the date, but during rebasing the normal git behavior is usually sane.
I agree that it's pretty confusing that github doesn't use the commit date in this case :confused:

**Comment by apotonick** [comment]
I merged @thegcat's test changes into https://github.com/apotonick/roar/tree/jsonapi - please help implementing it now! :wink:

**Comment by gottfrois** [comment]
Hey guys, how can we help you to finish the implementation?

**Comment by apotonick** [comment]
Cool, thanks @gottfrois! :heart: You could go through the JSONAPI tests in the jsonapi branch and make sure they really represent the specification. Once I finished chapter 10 of the Trb book I will get back to Roar and implement it (and will probably ask you for help, again). :wine_glass:

**Comment by gottfrois** [comment]
https://github.com/apotonick/roar/pull/154/files

**Comment by undergroundwebdesigns** [comment]
Any update on when JSONAPI 1.0 support will be ready? I'm saw the json-api-10 branch, and would be happy to pitch in some time and effort if you like.

**Comment by apotonick** [comment]
I will push to master, maybe today, but you will have to update to Representable 2.4.0.rc1.

**Comment by apotonick** [comment]
JSONAPI 1.0 is now in Roar/master. I will start documenting here: http://trailblazer.to/gems/roar/jsonapi.html

**Comment by gottfrois** [comment]
:+1:

**Comment by thhermansen** [comment]
:+1:

Thank you all working on json api 1.0 support!
