### ISSUE TITLE
Missing reference to Roar in JSON-API

### ISSUE THREAD

**Issue by fgarcia** [apotonick/roar#142]
I am so glad I discovered Roar (specially the de-serialization) after a long day playing with all other options.

Right now my interest lies in JSON-API and I could not avoid noticing that Roar is not listed in the [oficial json-api website](http://jsonapi.org/implementations/)

I think Roar deserves a reference there. It could even be the first Ruby gem fitting both categories: server and client

Adding Roar to the list is just a pull request away. However I believe Roar maintainers are the one to decide when it must be done, because Roar will get extra attention for a feature that I am not sure how willing you are to support.

**Comment by apotonick** [comment]
Cool idea! We still need to support RC3/stable so maybe we wait until this is finished?

**Comment by fgarcia** [comment]
The main reason I avoided a pull request by myself to add Roar on the list was because I noticed the RC3 problem. 

I was not very sure if the extra attention would be troublesome for the ones doing the coding... but the ones listed already are not even that good solutions or complete. 

I leave it up to you guys

**Comment by apotonick** [comment]
I'm already in trouble and have been for the past 10 years, so, go, add it! :rocket: :beers:

**Comment by jrnk** [comment]
It's still not listed while it deserves to :wink: 
Stumbled upon this issue, created pull request  https://github.com/json-api/json-api/pull/910

**Comment by apotonick** [comment]
Let me know if it gets added. http://trailblazer.to/gems/roar/jsonapi.html

**Comment by jrnk** [comment]
It's added :) 
http://jsonapi.org/implementations/#server-libraries-ruby

**Comment by apotonick** [comment]
:heart: !!!!11oneoneeleven
