### ISSUE TITLE
Testing: to_xml -> from_xml with collections.

### ISSUE THREAD

**Issue by akashirin** [apotonick/roar#144]
Hello.

I'd like to use Roar in a Sinatra-based project that provides an XML API. Trying to be convinced that the from_xml of a to_xml's output produces the original data. All is ok until using collections of compound objects. For example:
```
class Song < OpenStruct  
end
class Comp < OpenStruct  
end

class CompDecorator < Roar::Decorator
  include Roar::XML
  property :name
end

class SongDecorator < Roar::Decorator
  include Roar::XML
  property :title
  collection :composers, decorator: CompDecorator, class: Comp
end

song = Song.new(title: "Roxanne", composers: [Comp.new(name:"Sting"), Comp.new(name:"Stu Copeland")])
puts "INPUT:    " + song.inspect

doc = SongDecorator.new(song).to_xml
puts "TO_XML:   " + doc

song = Song.new
SongDecorator.new(song).from_xml(doc)
puts "FROM_XML: " + song.inspect
```
Output:
------
```
INPUT:    #<Song title="Roxanne", composers=[#<Comp name="Sting">, #<Comp name="Stu Copeland">]>
```
```
TO_XML:   <song_decorator>
  <title>Roxanne</title>
  <comp_decorator>
    <name>Sting</name>
  </comp_decorator>
  <comp_decorator>
    <name>Stu Copeland</name>
  </comp_decorator>
</song_decorator>
```
```
FROM_XML: #<Song title="Roxanne">
```
The same result when i'm using the Extend strategy (- representers instead of decorators).
Am I misunderstanding something? 
Please help. Thx.

**Comment by apotonick** [comment]
That looks odd - can you make sure you tried the same with `module` representers (you said you used `:extend` but please make sure the representers are modules.

In the first place, I don't understand why there's `comp_decorator` etc in your markup?!

**Comment by akashirin** [comment]
Thanks for quick reply. Yep, I'd tried the :extend also. Instead of 'song_decorator'/'comp_decorator' I get 'song'/'comp', accordingly. It's ok. However the end result of the from_xml is the same -- collection field is not created.

**Comment by akashirin** [comment]
PS. I used the :extend with modules of representers of course.

**Comment by apotonick** [comment]
I haven't used XML in years, I guess you have to do this.

```ruby
collection :composers, decorator: CompDecorator, class: Comp, as: :composer/:comp_decorator # whatever the wrapping item tag is named.
```

**Comment by akashirin** [comment]
I've tried:
```
collection :composers, decorator: CompDecorator, class: Comp, as: ':composer/:comp_decorator'
```
Unfortunately:
```
... in `evaluate': Invalid expression: :composer/:comp_decorator (Nokogiri::XML::XPath::SyntaxError)
```

**Comment by apotonick** [comment]
Haha that's not what I meant! You have to try either `:composer` or `:comp_decorator` for `as:`, dependent on how your XML looks like. Representable doesn't know where to find the collection items, so you have to tell it. Unfortunately, I found out that I did not properly document that, yet!

**Comment by akashirin** [comment]
It helps. Thank you.

**Comment by apotonick** [comment]
Cool! Please close this ticket if that solved your problem. :beers:
