### ISSUE TITLE
`embedded: true` and `render_nil: false` don't work with each other

### ISSUE THREAD

**Issue by juhijariwala** [apotonick/roar#146]
We'd like for roar to not render `_embedded` properties if they are set to `nil`.

Here is our test case (and the resulting error message) to demonstrate the problem and what we're expecting.

Is there a way to not render empty `_embedded` property?

```ruby
require 'bundler/setup'
require 'rspec/autorun'
require 'roar/decorator'
require 'roar/json'
require 'roar/json/hal'

describe 'Roar::Decorator' do
  class Person
    attr_accessor :name, :spouse, :city

    def initialize(name, city)
      @name = name
      @city = city
    end
  end

  class PersonRepresenter < Roar::Decorator
    include Roar::JSON::HAL

    property :name
    property :city, render_nil: false
    property :spouse, embedded: true, decorator: PersonRepresenter, render_nil: false
  end

  it "should not render empty _embed" do
    bob        = Person.new('bob', 'New York')
    alice      = Person.new('alice', nil)
    bob.spouse = alice

    expect(PersonRepresenter.new(bob).to_hash).to eq({"name" => "bob", "city" => "New York", :_embedded => {"spouse" => {"name" => "alice"}}})
  end
end
```

```
expected: {"name"=>"bob", "city"=>"New York", :_embedded=>{"spouse"=>{"name"=>"alice"}}}
     got: {"name"=>"bob", "city"=>"New York", :_embedded=>{"spouse"=>{"name"=>"alice", :_embedded=>{}}}}

(compared using ==)

Diff:
@@ -1,4 +1,4 @@
-:_embedded => {"spouse"=>{"name"=>"alice"}},
+:_embedded => {"spouse"=>{"name"=>"alice", :_embedded=>{}}},
 "city" => "New York",
 "name" => "bob"
``

**Comment by doughsay** [comment]
We're running into the same issue.  We've also tried `render_empty: false` with the same outcome.  The `_embedded` key is rendered no matter what.  Is this a problem in roar/json/hal?

**Comment by jasonchaffee** [comment]
+1

**Comment by apotonick** [comment]
That's a problem with my implementation of HAL, yes, and, you're lucky, because I started working with that very module in my book, so I might be able to fix it today. :grimacing:

**Comment by jgyllen** [comment]
Awesome. Thanks @apotonick !

**Comment by apotonick** [comment]
What about the following case, where a `collection` is the `embedded: true` candidate?

```ruby
{ "name":"Rails",
  "_embedded":{"authors":[]},
  "id":2,"_links":{"self":{"href":"/api/things/2"}},"comments":[]
}
```

The second line, should that simply be omitted or what's the general rule here?

**Comment by jasonchaffee** [comment]
According to the HAL spec, you should not omit links in preference of embedded or vice versa.  So, if you omit it, you would still have link to authors.  However, you would have to make a call to that link to find out it is empty.  

For embedded, it says this:

   "Embedded Resources MAY be a full, partial, or inconsistent version of
   the representation served from the target URI."

Thus, if it is an empty array, but not a nil array I think it should be rendered.  Thus, the implementor can send a nil array and use render_nil: true to not show it or they can send an empty array and have it shown or they can use :if to check the size of the array fi they don't want to show an empty array.

Just my 2 cents.

**Comment by apotonick** [comment]
Thanks @jasonchaffee, really helpful! I just realised that this is one and the same thing: If you `:render_nil` for `property` and `:render_empty` for `collection is set to false, it is up to the API dev. :+1:

**Comment by jasonchaffee** [comment]
As long as :render_nil, :render_empty, and :render all work for a collection, we are good.
