### ISSUE TITLE
Determining which format is rendered from within Representer

### ISSUE THREAD

**Issue by konung** [apotonick/roar#148]
Hi.

I was wondering if there is a way ( other than specifying an arguments when invoking a representer) , to determine which format is being requested from within a representer

I need something like this - see representaion_wrap - I need idiferent wrapping for JSOn and for XML

```ruby
class ProductRepresenter < Roar::Decorator
  include Roar::JSON
  include Roar::XML
  self.representation_wrap= lambda{|args| args[] ? "wrap xml" : "don't wrap json"}
end
````

Thank you

To clarify 

representation_wrap is set to nil - which is fine for JSON, but in xml it's causing a problem. Shouldn't this be set to <xml> at least?

````xml
<>
    <id>103323</id>

</>
````

**Comment by apotonick** [comment]
You can pass the format into the `to_json/xml` call.

```ruby
object.to_xml(format: :xml)
```

This can then be used in the `representation_wrap` lambda.

```ruby
lambda { |args| args[:format] == :xml ? "wrapXml" : nil}
```

BTW, ehm, just saying, but Representable does _not_ support two representers in the same module/class officially. If that works for you that's great (and I'm actually planning to support it ) but be careful, cowboy!

**Comment by konung** [comment]
Thanks Nick. 
I saw you give a similar answer in another question, but I was wondering if there an internal mechanism that would tell me which format is being rendered. Without resorting to passing parameters. I mean technically when I make the call to api.dev/product/1.xml - I already tell the system which format I want. 

 Yahoooo!

**Comment by apotonick** [comment]
The idea is (was??) that one representer stands for one format, so it implicitly knows what format it is. With my upcoming changes that allow multiple representers we could think about a `:format` option being passed in `options`.

Also, I wonder if your approach really works (conceptually)? Can you really keep two syntactically really different formats in one representer? Whooooooooooo!

**Comment by konung** [comment]
To respond to the second part of your question. I think it does in 80% of cases, based on my experience. IF the XML you are consuming / have to produce  - is not some over-engineered Goliath with weird namespaces & and bunch of data in XML tag attributes, than your XML should be very similar to your JSON ( structurally) . IF you are in the unlucky 20% - than you probably do have to maintain 2 separate Representers. I'm dealing with some Automotive industry XML produced by a huge monolithic JAVA system that decided to abuse the hack out of XML - and I'm the sorry soul that has to deal with it. I'm actually using ROXML& SAVON  in my legacy  app to consume / produce it - but as we are bringing this app into a new ERP - I'm trying to implement it using same tools I use in the rest of the app.
