### ISSUE TITLE
Using with json-api 

### ISSUE THREAD

**Issue by garytaylor** [apotonick/roar#152]
I have literally just picked up roar today as our project is already using json-api for its json output.
However, we now want to parse it into our models as well, so a switch to roar is being considered for input and output.

However, I am struggling with the json-api output.  I expected to see "data" in the output automatically and I expected to see support for relationships etc..  But, the relationship methods such as "has_one" etc.. all seem to refer to inserting links into the document.
Also, are compound documents supported ?  As far as I can see, there should be an "included" property in the output with these in, but I cannot find any reference to this.

Am I doing something wrong here ?  Am I expecting the gem to give me too much help and I should be defining all these things myself ?

**Comment by apotonick** [comment]
It's all good, I just did not have the time to work on JSON-API and after they kept changing the API, I gave up (for now). 

Our progress is documented here: https://github.com/apotonick/roar/pull/143 As you can see, most of the functionality is there but slightly diverging from the standard and needs to get fixed. Once this is done, you shouldn't have to define a lot yourself (which is the whole point of media types).

My apologies for the delay, I am hoping to be able to work on the `JSONAPI` module this month. :beers:

**Comment by garytaylor** [comment]
Hi Nick,
Can I try the branch with these changes in ? It's just for a proof of
concept so doesn't need to be totally complete.
I can also contribute.  Ive just spent 3 weeks getting a jbuilder extension
done for json-api but I much prefer roar over jbuilder for many reasons.

Thanks

Gary

**Comment by apotonick** [comment]
Please do!!! :smiley_cat: As you can see in @thegcat's branch, it shouldn't be that hard to make Roar JSON-API-1.0-compliant.

Also, if you could help, that would be amazing (especially you having explored all the format details already). I might spend a few minutes trying to merge together things so it'll be a bit easier for everyone to keep track. I'll let you know in a few mins.

**Comment by apotonick** [comment]
Ok, let's continue chatting on https://github.com/apotonick/roar/issues/141 - as you can see there, I pushed a new branch https://github.com/apotonick/roar/tree/jsonapi, let's make it happen!
