### ISSUE TITLE
Is it possible to prevent empty _embedded element?

### ISSUE THREAD

**Issue by eterps** [apotonick/roar#159]
Is there a way to prevent this ouput?

```json
"_embedded": {
},
```

render_empty: false works just fine, but if nothing else remains to be embedded Roar produces empty _embedded like above.

**Comment by apotonick** [comment]
You must be kidding, I just fixed that a few hours ago hahaha! https://github.com/apotonick/roar/issues/146 :laughing: Please update to 1.0.2.

**Comment by eterps** [comment]
Cool, I will give it a try. Thanks!

**Comment by eterps** [comment]
It works :+1:

**Comment by eterps** [comment]
Hmm, I still have to investigate the exact cause, but I get the feeling that this 1.0.2. release breaks embedded: true on the property method (while embedded: true does not have this problem for the collection method).

**Comment by eterps** [comment]
```ruby
module Bar
  property :foo, as: 'b:foo', embedded: true
end

OpenStruct.new(id: 12, foo: {}).extend(Bar).to_hash
```

gives:

```ruby
{"b:foo"=>{}, "id"=>12}
```

In previous versions it would give:

```ruby
{"_embedded"=>{"b:foo"=>{}}, "id"=>12}
```

**Comment by eterps** [comment]
Ok, it is caused by → as: 'b:foo'

**Comment by apotonick** [comment]
Can you please test from master? I will release 1.0.3 if it works for you! :beers:

**Comment by eterps** [comment]
Yes, everything works fine now. Thanks! :beers:
