### ISSUE TITLE
Double encoded ouptut

### ISSUE THREAD

**Issue by blinduck** [apotonick/roar#164]
I'm building a hypermedia API and trying out Roar. I've just been following the basic setup.

```
require 'roar/json'

module UserRepresenter
  include Roar::JSON

  property :name
end
```

I have a user object with the `name` property. 
When I try 
```
user.extend(UserRepresenter)
user.to_json
```

I get a double encoded string -> `"{\"name\":\"John\"}" `
Any idea what's going on?

**Comment by apotonick** [comment]
This is correct JSON, Ruby only displays it oddly. Actually, this is not a double-escape but a simple string escape in the document.

If you want a hash, do `user.to_hash`. You can then call `to_json` (from the standard JSON implementation) on that hash, and you will get the same result.

```ruby
hash = user.to_hash #=> {"name"=>"Deepan"}
JSON.generate(hash) #=> "{\"name\":\"John\"}"
```
