### ISSUE TITLE
JSONAPI: Single-resource compound documents are non-conformant

### ISSUE THREAD

**Issue by dvogel** [apotonick/roar#171]
Resource decorator classes (and probably modules, haven't tested though) render non-conformant documents when related resources are included. Specifically, the `included` attribute is supposed to be at the top level rather than embedded inside the `data` object. Example: [The document in this test](https://github.com/apotonick/roar/blob/master/test/jsonapi/render_test.rb#L40) does not conform to [the JSON Schema definition](http://jsonapi.org/faq/#is-there-a-json-schema-describing-json-api) provided by the JSONAPI project.

**Comment by apotonick** [comment]
Thanks! Is that only the `included`?

BTW, dropping modules soon in Representable. `JSONAPI` only works with decorator classes. :wink:

**Comment by dvogel** [comment]
Yeah, if I remove the `included` attribute from the document, the JSON schema validator is happy.

**Comment by apotonick** [comment]
Give me a few...

**Comment by apotonick** [comment]
Can you check now? Thanks!

**Comment by dvogel** [comment]
Much better now. Thanks!
