### ISSUE TITLE
Roar::Hypermedia in version 1.0.3 refer to Representable::Inheritable that was removed in Representable 2.4.0 

### ISSUE THREAD

**Issue by nonnenmacher** [apotonick/roar#172]
Sound like the current version of Roar 1.0.3 still reference Representable::Inheritable that was removed from Representable 2.4.0.

```
 module LinkConfigsMethod
      def link_configs # we could store the ::link configs in links Definition.
        representable_attrs[:links] ||= Representable::Inheritable::Array.new
      end
    end
```

the Roar commit 323319da9a6753b4181b6593a709e6a77ae832a3 removed that properly, but this is on the current (next version) source, still in the 1.0.3 tagged release.

So a simple bundle update, break things for me.

**Comment by nonnenmacher** [comment]
a simple 

```
gem 'roar', github: 'apotonick/roar'
```

in Gemfile, fix the problem in the interim, until next version bump, so this is not a big issue.

**Comment by apotonick** [comment]
Oh, I will release Roar 1.0.4 with Representable < 2.4. Thanks!
