### ISSUE TITLE
Nested and to_json method error:  wrong number of arguments (0 for 1)

### ISSUE THREAD

**Issue by alaibe** [apotonick/roar#176]
Hi,

I am not sure what I am doing is correct so may be not an issue.
Here is my representer:
```  
module OperationRepresenter
    include Roar::JSON

    property :status
    property :headers
    property :body
    property :path
    property :method

    nested :data
  end
```

Client::Operation is the class who use the OperationRepresenter
Client::Customer is another class using the another representer

Then when I do:
```
Client::Operation.new(
  method: :post,
  data: Client::Customer.new(first_name: 'first_name'),
  path: "path"
).to_json
```
I get an error:
```
ArgumentError: wrong number of arguments (0 for 1)
representable-2.3.0/lib/representable/binding.rb:101:in `method'
```

The data property should not be static, it can be Client::Customer or Client::Anything.

Does someone have an idea?
Thanks

**Comment by apotonick** [comment]
The way you use `nested` is incorrect - it's meant to map to a nesting in the _document_, not in your represented object. Also, `nested` only makes sense with an inline representer: http://trailblazer.to/gems/representable/3.0/api.html#document-nesting

**Comment by alaibe** [comment]
Thx for the answer, I finally found what was my problem, not what I though in the first place.
Having
```ruby
property :method
```
Causes some problem with the interpolation, at some point in the stack there is this call:
```ruby
  send(method)
```
For my case I just renamed `method` in `http_method`

**Comment by apotonick** [comment]
Oh yeah, the good old `method` problem! :grimacing:
