### ISSUE TITLE
Roar::Hypermedia uninitialised constant Representable::Inheritable

### ISSUE THREAD

**Issue by kipcole9** [apotonick/roar#179]
Roar::Hypermedia 1.0.3 (and I think 1.0.1) refer to Representable::Inheritable which appears to have disappeared after Representable 2.3 (I think).  Means Roar::Hypermedia isn't compatible with later versions of Representable.  Error detected using Representable 2.4 and Representable 3.0 but its Roar that is making the reference.

    NameError: uninitialized constant Representable::Inheritable
    from /Users/kip/.rvm/gems/ruby-2.2.2/gems/roar-1.0.3/lib/roar/hypermedia.rb:50:in `link_configs'
    from /Users/kip/.rvm/gems/ruby-2.2.2/gems/roar-1.0.3/lib/roar/hypermedia.rb:128:in `link'

**Comment by apotonick** [comment]
Please upgrade to Roar 1.0.4.

**Comment by kipcole9** [comment]
Nick, thanks for the response.  I think 1.0.4 has a dependency challenge:

Bundler could not find compatible versions for gem "representable":
    In Gemfile:
      roar (= 1.0.4) ruby depends on
        representable (< 2.4.0, >= 2.0.1) ruby

Meaning it won't run with either Representable 2.4 or 3.0.  An unintended regression?

**Comment by apotonick** [comment]
Sorry, no! :grimacing: Roar 1.0 doesn't work with Representable > 2.4. You have to pull `roar/master` until I release 1.1, which should happen "this year" haha.

**Comment by kipcole9** [comment]
Thanks Nick, no problem, I'm running on edge rails so whats one more flexible moving part!

**Comment by apotonick** [comment]
Rails 5? lol

**Comment by kipcole9** [comment]
I enjoy the pain :-), but actually its working out pretty well for me.
