### ISSUE TITLE
How to conditionally include representer

### ISSUE THREAD

**Issue by jonsgold** [apotonick/roar#197]
How do I include a representer within another representer based on a condition?

For example:

```
module GroupRepresenter
  include Roar::JSON
  include OneRepresenter, if: lambda { |args| args[:a_param] }
  include TwoRepresenter, if: lambda { |args| !args[:a_param] }
end
```

**Comment by apotonick** [comment]
http://trailblazer.to/gems/representable/3.0/function-api.html#extend

**Comment by jonsgold** [comment]
Thanks, as I understand this can be used per one property. Is there any way to **include** a representer that presents all properties?

**Comment by apotonick** [comment]
`include` is from Ruby, and run at compile-time, there's no run-time environment, yet. You should use `:extend` for that, you can extend multiple modules. Again, this is all pure Ruby and has nothing to do with Roar. :wink:
