### ISSUE TITLE
Feature request: camelcase field naming

### ISSUE THREAD

**Issue by adamburmister** [apotonick/roar#57]
I'm working on a JSON HAL API and using roar for it, which is great btw.

One thing on my wishlist before I hit production is camel-casing the JSON response properties.

I thought I would raise a ticket to discuss possibilities of implementing this. If you can point me to the right spot I should be able to help make the changes.

**Comment by apotonick** [comment]
You can implement that using `defaults` now.

**Comment by kostyadubinin** [comment]
@apotonick, what is `defaults`?

**Comment by apotonick** [comment]
http://trailblazer.to/gems/representable/3.0/api.html#defaults
