### ISSUE TITLE
parse_strategy feature should allow richer matching with existing linked or embedded resources

### ISSUE THREAD

**Issue by joshco** [apotonick/roar#85]
I've got a model for People and Addresses.  People have many addresses.
In my PersonRepresenter, I've got:

     collection :addresses, :class => Address, :extend => AddressRepresenter, 
     :embedded => true , :parse_strategy => :sync

I initially stumbled upon the sync thing because I noticed that if I did a POST of a person, but didn't include the _embedded address array, it would delete my existing address collection for a given person.

Note, I'm doing some matching on POSTs.  If you do a post of a person and the server finds that a matching person already exists then it passes the existing person object to the consume! call in the person controller.

Is there a way I can:
1) If a collection property is not present in the request to the server, then leave the collection alone.  Dont get rid of it.
2) control how parse_strategy does its matching?  How does it know which record it is supposed to be updating?

**Comment by apotonick** [comment]
Parse strategies got superseded by populators which are way more intuitive. http://trailblazer.to/gems/representable/populator.html

**Comment by joshco** [comment]
that link doesnt work

**Comment by apotonick** [comment]
I know, still writing it! :wink:

**Comment by joshco** [comment]
hurry up! :)

**Comment by abinoam** [comment]
@apotonick https://github.com/apotonick/roar#syncing-objects still cites ```:parse_strategy```
