### ISSUE TITLE
HAL embedded nesting depth / zoom?

### ISSUE THREAD

**Issue by kookster** [apotonick/roar#90]
I've made some real progress implementing a HAL api using roar and rails, but I have a problem I haven't been able to figure out yet.

I have some property/collections that are embedded, which works great, however, I also want to be able to NOT embed them when the resource is itself is embedded.

If you retrieve a `story`, it comes with with an embedded `account`, and that's good for getting that one single story.

But, if I retrieve a list of stories, then I do not want each one to have the account embedded, only a link to the account in each.

I think of this as a kind of embed depth - I want to embed one level down, but I don't want an embedded resource to have any embeds of its own.  In a perfect world, you could control this depth.

What I can't figure out is how to know the current depth in the context of deciding to included an embedded resource.  I was thinking if I did, I could use it in an overridden  `skip_property?`, since what I am trying to do is skip it based on embed depth:

https://github.com/apotonick/representable/blob/master/lib/representable/mapper.rb#L44

Any ideas on how to figure out depth, or how I could add tracking this depth?

**Comment by apotonick** [comment]
Let me know if this is still desired. The `HAL` implementation is greatly simplified in 1.1.
