### ISSUE TITLE
Code in "link" appears to run in the Decorator's context, not the represented object's

### ISSUE THREAD

**Issue by simonsouth** [apotonick/roar#92]
I'm trying to serve HAL representations for a REST API using Roar inside of Grape. I have a decorator class very much like the example shown in the README to represent an ActiveRecord model:

    class SongRepresenter < Roar::Decorator
      include Roar::Representer::JSON::HAL
      include Roar::Representer::Feature::Hypermedia
      include Roar::Decorator::HypermediaConsumer

      property :title
      property :artist

      link :self do
        "/songs/#{id}"
      end
    end

But when I load the page for a Song resource, I get this:

    NameError at /songs/80
    undefined local variable or method `id' for #<SongRepresenter:0x95c0cac>

as though the "id" method is being invoked on the representer itself, not the object it is supposed to be representing.

If I remove the `#{id}` portion of the link URI, everything works fine. Changing `id` to `title` doesn't help.

The same thing happens with the current release of Roar and representable as well as with the latest code for both in Github.

I can't see what I'm doing wrong. Is there something I've overlooked, or do we perhaps need a `Roar::Decorator::HypermediaProducer` as well?

**Comment by johnhamelink** [comment]
Please merge this! I spent a good hour trying to figure how to get individual items' collections to show and the answer was to use `include Representable::JSON` as well as `include Representable::JSON::Collection`.

**Comment by apotonick** [comment]
This is not a PR and no test has been written by anyone. Why do I always have to do all the work?

**Comment by apotonick** [comment]
@johnhamelink I am not sure if we're talking about the same problem. Can you please explain what you mean? I think you were trying to render a [lonely collection](https://github.com/apotonick/representable#lonely-collections) which is unrelated to this issue.

**Comment by johnhamelink** [comment]
Woah there! Who said you had to do any work? :smile:  I must admit I didn't read through the comment log but I looked through the code and in frustration I responded a bit haphazardly - I apologise if I seemed demanding!

I was trying to render a lonely collection and some of the code in this issue allowed me to render correctly whereas it would not render correctly before.

An example:

```ruby
module FixtureDetailsRepresenter
  include Representable::JSON
  include Representable::JSON::Collection
  items extend: FixtureDetailRepresenter, class: Fixture
end
```
```ruby
module FixtureDetailRepresenter
  include Roar::Representer::JSON
  include FixtureRepresenter

  property :deleted

  collection :players,
             extend: PlayerRepresenter,
             class: Player
end
```

(both Fixture and Player are ActiveRecord classes in this example)
If `include Representable::JSON` is omitted from `FixtureDetailsRepresenter` then `players` will not show up and it seems that `FixtureDetailRepresenter` is effectively ignored.

This affects me quite a lot, so I'll happy submit a PR to wrap this in a helper module and add documentation (unless you think this should be handled differently?)

Hope that makes things a bit clearer?

**Comment by apotonick** [comment]
Haha, no problem @johnhamelink ! :laughing:

This is so not the correct thread for your problem haha. I agree that including `Representable::JSON::Collection` should include `Representable::JSON` - why is that not happening?

**Comment by johnhamelink** [comment]
That's a good question. You're right, this is the wrong place - I think this is more likely a Representable bug. It seems like [this bug](https://github.com/apotonick/representable/issues/56) is likely caused by the same issue, so I'll jump over to there.

Thanks @apotonick :smile_cat:

**Comment by apotonick** [comment]
That looks odd. Roar 1.0 doesn't have the `Representer` namespace anymore. http://nicksda.apotomo.de/2015/01/roar-1-0-released-with-json-api-support/ Other than that, I really don't know what could be wrong.

**Comment by johnhamelink** [comment]
Yup, I was using 0.12.9 - something between that release and 1.0 fixed my issue.
